### ISSUE TITLE
Rewrite in something more portable

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/catberry-ts#4]
The codebase should be rewritten in something other than PowerShell because of portability reasons. TypeScript should be a good candidate.

**Comment by rexim** [comment]
+1

**Comment by rexim** [comment]
I may take this one if you don't mind.

**Comment by ForNeVeR** [comment]
Okay!​

**Comment by rexim** [comment]
Resolved in 4661c6f53b9b8281556f391689a956725b5e364b Sorry, forgot to add a proper comment to close this automatically. :)

**Comment by ForNeVeR** [comment]
Very well, I've verified this and it is okay.
